### ISSUE TITLE
Document design

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#1]
Need to have some top-level documentation explaining tradeoffs and design decisions. This makes it easy for others to contribute later.

**Comment by JaseMiller** [comment]
**I agree**. Great idea. Does your core team have thoughts on this already, or are you looking for some ideas?

**Comment by durden** [comment]
@JaseMiller We have some ideas but would love to hear more.  We have a lot of documentation on the design tradeoffs, but it's mostly in my paper notebook right now. So, I want to publish those docs first then hopefully that will kickstart a conversation on architecture and ways to improve.

**Comment by JaseMiller** [comment]
**Sounds perfect**. I look forward to seeing what you have and interacting once you get it in digital form.
Cheers,
JASE

**Comment by durden** [comment]
@JaseMiller Thanks for the feedback.  The big design decisions so far have been using branches instead of forks for different versions and edits of a guide.  The reason we use branches now is because it's easier to do without async stuff via the API and also we can ask for less permissions up front when you authenticate the app for your github account.

**Comment by JaseMiller** [comment]
Nice. I think that's a good call, too. I look forward to it. Thx!

**Comment by durden** [comment]
Updated the latest docs with more information on the layout of the content repo and why we're using branches for the time being.

http://hacker-guides-cms.readthedocs.org/en/latest/github_repo_layout.html
