### ISSUE TITLE
Title uniqueness

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#11]
Currently we must guarantee article titles are unique across the entire repository. The reason is we base several things on the title:
1. URL to article - /review/<slugified_title>
2. Markdown file in article repository - repo/<slugified_title>/article.md

This has a few annoying consequences:
1. Two users cannot have the same article title
2. It's not obvious in the UI that this is a restriction.

A user will get a generic 'cannot create file' error when creating a new article with a duplicate title.
The error is due to not providing the commit SHA with the API call. Github doesn't see this as a new markdown file because of the duplicate name, thus it expects an existing SHA.

Not entirely sure what we want to do here, but we definitely want the error scenario above handled more gracefully. We could detect the duplicate title and do something like one of the following: - Change title/markdown file to include some timestamp to make it unique - Use usernames in article URL, something like: /<github_username>/<slugified_title> - We'd need to account for using a different markdown filename in the article repository.

**Comment by smiller171** [comment]
I like the idea of putting the author's name or user name in the URL.

Normally I like a date in the article URL, but I think the hope here is that these articles will be updated and then the date would not be representative of the content.

**Comment by durden** [comment]
Exactly.  We're thinking of the guides as living documents.  I also like the author name in the url.

**Comment by durden** [comment]
Comment from Peter Kellner via slack:

"""
I would suggest moving it through a workflow that creates a url that is only visible to the author and then when you publish it use the author's github handle and the title as the only permanent link the article will ever have publicly.  Then, on the article, if the author is auth'd in, show a list of status changes so the author knows what is going on (including things like "pending publish", "pending review", etc.
"""

**Comment by smiller171** [comment]
I think that's on the right track

**Comment by durden** [comment]
I'm going to consider this 'fixed'.  This problem is lessened by the recent change to use the 'stack' in the article URLs.  Now the canonical article URL is `/<stack>/<title>` so title's now can be duplicated as long as their stacks are not.

We've also improved the error message when the unlikely name clash between `<stack>/<title>` happens.  See [this commit for more information](https://github.com/pluralsight/guides-cms/commit/beb7f9acb1c818c4cafed6e2f89071fa9c4a2ed7).

Also, we've recently changed the publish status workflow similar to the comment from Peter Kellner above.  You can read more about that workflow [here](http://hacker-guides-cms.readthedocs.org/en/latest/publish_workflow.html).

**Comment by paulocheque** [comment]
I guess we will need to use some database to maintain the data consistent eventually.

We could have periodic async tasks to "copy" the DB data into GitHub special files (published.md etc).

**Comment by durden** [comment]
@paulocheque That's a good plan.  I'm just trying to avoid adding a database dependency and syncing as long as possible.  Syncing always seems easy but never ends up that way.
