### ISSUE TITLE
Initial creation of an article does not update your author page

### ISSUE THREAD

**Issue by smiller171** [pluralsight/guides-cms#17]
After publishing an article in the web UI, my user page does not list it. My user page does list the article after I submit an edit.

**Comment by durden** [comment]
It's a caching issue.  I increased the caching timeouts just for launch.  Trying to stay up with beta under the traffic ;)

**Comment by durden** [comment]
I'll be lowering the cache timeouts during the week as we see how things hold up against the github API limit, etc.  As of now it could take maybe 15 minutes or so for your article to show up on your user page.  I'll continue tweaking it as we go along.

**Comment by smiller171** [comment]
thanks for the info. must have been coincidence when it updated for me.
