### ISSUE TITLE
Suggest that built in editor support wysiwyg and html in addition to markdown

### ISSUE THREAD

**Issue by pkellner** [pluralsight/guides-cms#18]
Otherwise, you are creating to exclusive a community.

PS:  I hate markdown.  I maybe the only one though.

**Comment by durden** [comment]
Great point. Our current editor does support html and markdown.  However, we're hoping to customize things so you don't have to know markdown in the long run.

We're also discussing several open source editors as a replacement:  See this [thread for the choices so far](https://github.com/pluralsight/guides-cms/issues/2).

In short, we're thinking of having two editor experiences, 1 for markdown and 1 withs something like this [medium clone for wysiwyg](https://yabwe.github.io/medium-editor/).

**Comment by durden** [comment]
We're testing a new editor that will be rolled over to production.  You can try it out [here](http://pskb-stage.herokuapp.com/write/).  This editor supports HTML and markdown.  It also has a live preview to help with the WYSIWYG aspect.  Let us know what you think!

**Comment by durden** [comment]
Closing this as our new editor supports full screen, HTML, and markdown.  It's not quite a WYSIWYG approach because we decided a live-preview was better for our developer-oriented audience.  Please feel free to open a new issue for any suggestions you have with the new editor!
