### ISSUE TITLE
Improve editing experience

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#2]
We're currently using the [Epic Editor](http://epiceditor.com), but the UI could be greatly improved.  The main requirements at this point are:
- Default to full-screen side-by-side editing with live preview
- Button to exit full-screen mode

**Comment by durden** [comment]
I've setup the [bootstrap editor](http://www.codingdrama.com/bootstrap-markdown/) on the [testing site](http://pskb-stage.herokuapp.com).  I really like this and that version also has image uploads implemented.

**Comment by durden** [comment]
Other options for editors to explore:
- [Medium clone](https://yabwe.github.io/medium-editor/)
- [Dillinger](http://dillinger.io)

I love the look of Dillinger, but it has quite a bit of dependencies.  Maybe we could trim that down and make it simpler?

**Comment by durden** [comment]
I've also played around with the medium clone editor this week too. It works and seems ok, but I'm not sure it's the right fit for our audience at this time. We're very developer focused right now and the medium editor doesn't deal with markdown at all. It looks great but creates HTML output which is hard to diff and read on github.com. There are plugins to convert the medium html to markdown, but I'm not sure if going down that route is worth it.

Also, the medium editor doesn't deal with code blocks at all. We can always customize the medium editor to do a lot of this if we want to go that route.

What do you guys think?

I like the medium editor but seems more fit for long-form prose instead of tutorials. Maybe this is OK though?

**Comment by durden** [comment]
Here's another [editor idea Facebook just released](http://facebook.github.io/draft-js/). Maybe it's worth investigating too?

**Comment by shadowcodex** [comment]
Might I suggest a look at https://stackedit.io/ as well?

I prefer them over Dillinger

**Comment by durden** [comment]
@shadowcodex I've actually played with stackedit.io and it's pretty nice.  I personally like the UI on Dillinger better.  My hesitation with both is the amount of dependencies and complexity though.

**Comment by durden** [comment]
Here's a few others we've put on the list to evaluate:
- https://cloose.github.io/CuteMarkEd/
- https://stackedit.io/editor
- http://25.io/mou/
- http://pad.haroopress.com/

**Comment by shadowcodex** [comment]
I agree with you, but it is something you could easily whip up a clone of on stackedit.io.

I haven't seen some of those. I'll have to look at them.

**Comment by paulocheque** [comment]
I will just put some comments that I investigate so far. I will focus in the Dillinger right now.

| Option | Embeddable | Live preview | Auto-saving | Themes | Line numbers | Angular plugin | obs | link |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Dillinger | no | yes | yes | no | yes | no |  | https://github.com/joemccann/dillinger/issues/509 |
| EpicEditor | yes | yes | yes | yes | no | no |  |  |
| StackEdit | no | yes | yes |  |  |  |  | https://github.com/benweet/stackedit/issues/843 |
| PageDown | yes |  |  |  |  |  | old | imature http://samwillis.co.uk/pagedown-bootstrap/demo/browser/demo.html |
| ShowDown | yes | yes | ? | yes | ? | yes |  |  |

**Comment by durden** [comment]
Just wanted to reference @paulocheque great work on this issue via [this pull request](https://github.com/pluralsight/guides-cms/pull/30).

**Comment by durden** [comment]
Closing this due to this [this pull request](https://github.com/pluralsight/guides-cms/pull/30).
