### ISSUE TITLE
Bad link on Table of Contents

### ISSUE THREAD

**Issue by paulocheque** [pluralsight/guides-cms#29]
Use this example for the test: `What's preferred?`

I believe the `'` or the `?` chars are unescaped.

**Comment by durden** [comment]
Good catch.  I'll fix that.

**Comment by durden** [comment]
This solution works, but I'm not javascript expert.  Maybe there's a more elegant solution?

The only thing to be careful of is to make sure to replace spaces with `-` for backwards-comparability with any old links that were already created.
