### ISSUE TITLE
Make save endpoint more API-friendly

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#31]
It would be nice to be able to write a small script to create a guide via the command-line or without the web editor at all.  This could have lots of benefits:
- Allows users to write locally with their own editor and have a small plugin to grab the text from the editor and submit it to hack.guides().
  - For example, I wrote a [simliar script for vim](https://github.com/durden/codrspace_cli) that uses the [codrspace](http://codrspace.com) service's API.
- Makes it easier to automate the creation of guides at all
  - Some authors prefer to work directly with github.com and git.  So, this API endpoint would allow for easy creation of a [script to automate guide creation](https://github.com/pluralsight/guides-cms/issues/9).

**Comment by durden** [comment]
To do this we probably want to make the save endpoint take and return JSON.  This way the hack.guides() site can use the same endpoint as the scripts.  This will ensure the API endpoint keeps working since the website will be using it as well.  Looping in @paulocheque because I know he has some thoughts on how best to do this.

**Comment by durden** [comment]
This fix will most likely end up being part of [this pull request](https://github.com/pluralsight/guides-cms/pull/30).

**Comment by durden** [comment]
The bulk of this work was done in [this commit](https://github.com/pluralsight/guides-cms/pull/30/commits/5decc311d65d062bdd4bb5610cb50fccedcee742).  The only other thing we need to do to make this endpoint callable from a local script is some form of authentication.

Ideally we'd issue each github user some kind of API key and pass that along in the form data.  However, that's a little tricky without using a database.  Currently we're only using github.com for all persistent storage (and heroku environment variables).  So, any ideas on how we could do some kind of authentication without an external database?

Maybe we could use some kind of information from the authors' github account that is considered private?  Something like their primary email address or their oauth key that's already used by the website?  Guess we'd have to provide another API on our site to query for a user, log them into the site, and get their github oauth key and save it in the local script.  Just trying to toss around ideas.  Anyone else have suggestions, @paulocheque?

**Comment by paulocheque** [comment]
Hi, I guess eventually we will need to use a database. For example, for searching articles. But this would create a new approach for the system. Using your example, we would need to synchronize the article in case the user edit it directly via GitHub. Maybe we would need to add some post commit signal.

I guess we could try using the same GitHub auth token, but I believe the complexity would be the same or even harder than using an hack.guides api key. I guess we would need to add a new endpoint for authentication.

**Comment by durden** [comment]
I've actually implemented a crude article search already based solely on
the flat file listings in published.md, etc. See the search function in
article.py. It's not great just trying to keep things simple as possible.

**Comment by paulocheque** [comment]
I guess the solution is great, I was just wondering some more complex searches, like searching for words of an article or a huge amount of articles published. Maybe we would need to optimise it eventually and the solution could be the use of a NoSQL db. 

I am just trying to say that using a DB will increase the complexity of the environment, but we would get advantages too.

In summary, I believe we should use the original GitHub authentication or create our own solution (without using github attributes)

**Comment by durden** [comment]
Thanks for the input, lots of good ideas! I agree 100%. We could get a lot
of advantages by using a database and even something like mongo, etc. I
also like the post commit hook idea for syncing. That's something I've
thought a bit about but that could the best solution to syncing with GitHub
edits.Also, if we want to do real queries or searches based on text I say
we definitely move to a database. My solution now is way too slow and
cumbersome for doing anything more complicated that searching by title.

**Comment by durden** [comment]
The save point is API-friendly now.  It returns JSON and is used via AJAX in the app.  Ultimately we want to be able to submit a guide from a script, not the website.  This involves storing authentication credentials somewhere and doesn't have much to do with the save endpoint.  We'd need to make a few modifications to retrieve those credentials, but it has nothing to do with this issue.
