### ISSUE TITLE
Bug with editing a guide that has javascript tag in it

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#35]
Trying to edit a guide with javascript tags in it leads to javascript errors.  To reproduce on the production site do the following with one of these guides:
- [Intro to Test Driven Development in Javascript](http://tutorials.pluralsight.com/front-end-javascript/introduction-to-test-driven-development-in-javascript)
- [Angularjs Controllers](http://tutorials.pluralsight.com/front-end-javascript/angularjs-controllers)
## Steps to reproduce
1. Login
2. Click on one of the guides referenced below
3. Click the 'edit this guide' link in the left-sidebar
4. Now notice the text is not loaded into the editor and see the javascript console for exception

I debugged the issue and narrowed iit down to a simple test case which you can try on a [testing site](http://guides-dev.herokuapp.com/other/testing-javascript-tags?status=in-review).  It seems to be a problem with rendering raw text that has a javascript tag/source code in it.  The guides render fine on the guide page itself, just the editing view causes problems.

I'm guessing something isn't escaped or something related to that.

**Comment by durden** [comment]
Can you look into this @paulocheque ?

**Comment by paulocheque** [comment]
I was able to reproduce it.

It is a template issue related to the tag `</script>`. If you remove all `</script>` occurrences it is fixed.

I will find a solution now.

**Comment by durden** [comment]
Looks good.  Thanks!
