### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by NabaSadiaSiddiqui** [pluralsight/guides-cms#38]
While running **py.test** from the main repository directory (`python bin/py.test`), I ran into compilation errors because of certain missing modules (e.g. `ImportError: No module named mock`).

My fix is to update the **requirements.txt** file with these modules:

```
mock==2.0.0
nose==1.3.7
testscenarios==0.5.0
testresources==1.0.0
virtualenv==14.0.4
contextlib2==0.5.1
```

However, after updating the **requirements.txt** file and installing these missing modules, some of the test cases are failing. See the attached log file [output.txt](https://github.com/pluralsight/guides-cms/files/212313/output.txt)

Looking at some of these tests, its clear they are not testing the business domain. Which leads me to think I might be importing incorrect versions of the missing modules (see above).

@durden What do you think?

**Comment by durden** [comment]
You can fix this by running `py.test pskb_website` to run only the tests in this projects' main package directory. You should not need any of those modules to run the existing tests.  The only requirement for the existing tests is py.test.

Do you have your virtualenv setup in the same directory as the project you cloned from git?  The `py.test` command tries to find all tests in the current working directory by default.  So, if you have your entire virtualenv in the current working directory then `py.test` will try to run all the tests of your dependencies like celery, etc.

Another approach is to not store your virtualenv in the same directory you cloned from github.  For example, I put all my virtualenvs in `~/.virtualenvs/` on my machine.  This way the project directory I clone from github isn't cluttered with an entire `lib/` and `bin/` virtualenv setup.  However, this my personal preference.

**Comment by durden** [comment]
I updated the `test` rule in the Makefile to only run our projects' tests.  Let me know if this fix doesn't work.  Thanks for trying it out!

**Comment by NabaSadiaSiddiqui** [comment]
I had my virtualenv setup in the same directory as the project I cloned from Git. Storing my virtualenv in a different directory and then running `py.test` runs only the projects' tests.

Thanks for the fix!

**Comment by NabaSadiaSiddiqui** [comment]
As a side note, do you think it is a good idea to update the [docs](http://hacker-guides-cms.readthedocs.org/en/latest/index.html) with an additional section on how to add/run tests?

/cc @durden

**Comment by durden** [comment]
Definitely.  We should update the docs with a section on how to add and run tests.  Any suggestions on where to put that in?

**Comment by NabaSadiaSiddiqui** [comment]
We can put it in the section [Install for Local Development](http://hacker-guides-cms.readthedocs.org/en/latest/install.html#install-for-local-development), right below **Testing without browser**.

The other option is pull out **Testing without browser** from **Install for local development** section, and create a separate **Testing** section. We can add more content to this section (e.g. on how to run tests from py.test). And in addition to being accessible from the index in the side panel, we can reference this section at the end of **Install for local development**. I believe this new section should come right after **Install for local development** and before **Deployment**.

I prefer the second approach, because it will allow us to later add more content like our testing strategy, etc. without compromising the goal of **Install for local development** section

**Comment by durden** [comment]
Thanks for the suggestion.  I like the second approach too.  Lets go with that one.  Can you send a PR?

**Comment by NabaSadiaSiddiqui** [comment]
Sure!
