### ISSUE TITLE
Top left logo highlighted when showing bootstrap modal

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#52]
The new top left logo seems to highlight when trying to delete a guide.

<img width="1271" alt="screenshot 2016-04-26 09 59 07" src="https://cloud.githubusercontent.com/assets/58063/14810922/b39aa614-0b95-11e6-85fb-ca166b75ce3c.png">

Can we make the tweak the `z-index` or something to make the hover on the logo **not** work when a modal window is shown?  Another option would be to simply make sure the logo doesn't 'highlight' or stand-out so much when the modal window is shown.  Can you look into this @paulocheque?

**Comment by paulocheque** [comment]
Sure. It is a z-index issue. We have to check the bootstrap modal z-index value and adapt it.

**Comment by paulocheque** [comment]
Fixed in this PR.
