### ISSUE TITLE
Editor removes escape characters even if in a code block

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#64]
I think this is an issue with the new editor and loading data for editing a guide.  A guide might have text that looks like an escape character but in a code block.  For example:

```
abs(x) = \begin{dcases*}
        x & when `x \geq 0`\\
        -x & otherwise
        \end{dcases*}
```

The `\begin` starts with `\b` escape character, but it's not meant to be an escape character because it's in a code block.  The editor allows you to type this text and save it.  However, if we come back to this guide the editor strips the `\b` on load.

**Comment by durden** [comment]
@paulocheque Can you look into this?

Checkout [this small example](http://pskb-stage.herokuapp.com/other/guide-with-escape-characters?status=in-review).

Notice how the text renders fine on the rendered markdown page (above link).  Now, click the 'edit this guide' link to edit the guide.  Notice how the `\b` is striped.  This will result in changes to the original guide that the author did not intend.

I discovered this bug while testing with [this real-world guide](http://tutorials.pluralsight.com/c-c++/functional-style-programming-using-c?status=in-review).

**Comment by durden** [comment]
[Here's an example of a diff](https://github.com/pluralsight/guides/pull/40/commits/03dc98cdd17fba9e1530663c2cd41426f9047edb) where the editor removed what look like escape characters even though my real changes only changed one line, the header of the 'Introduction' line.

**Comment by paulocheque** [comment]
I guess I find a good solution. I will make more tests and commit/deploy for tests.

**Comment by paulocheque** [comment]
We were facing JS escaping problems for all JS special chars: http://www.w3schools.com/js/js_strings.asp

So now, I am using textarea to load the initial content of the article. It is much simpler and clean.

I am testing all the JS special chars and also our last issues related to escaping in these tests:
http://guides-dev.herokuapp.com/write/draft/python/testing-escape/?branch=master
http://guides-dev.herokuapp.com/write/draft/python/testing-escape-2/?branch=master

But I would like to test more on real articles, so I will make a copy of some of the production articles to check.

**Comment by paulocheque** [comment]
More testing articles with your examples:

http://guides-dev.herokuapp.com/write/draft/python/guide-with-escape-characters/?branch=master
http://guides-dev.herokuapp.com/write/draft/python/functional-style-programming-using-c/?branch=master

**Comment by durden** [comment]
Looks fixed to me, thanks again!
