### ISSUE TITLE
Javascript exception when editing a guide

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#84]
Tried to edit [this guide](http://tutorials.pluralsight.com/ruby-ruby-on-rails/how-to-install-ruby-on-rails-on-centos-7?status=in-review) and got a javascript exception preventing the preview from loading.

I haven't narrowed it down yet but maybe it's some missing tag, etc.? @paulocheque can you take a look at it?

**Comment by paulocheque** [comment]
Yeah, it is related to the unclosed html tag with the "`" inside of a code.

``````
    ```
    rails s -b <SERVER's PUBLIC IP>
    ```
``````

I am trying to find a solution.

**Comment by paulocheque** [comment]
Before the PR we had this issue:

Fail:

``````
    ```python
    <b>asd<b'>
    ```
``````

Success:

``````
    ```html
    <b>asd<b'>
    ```
``````
